# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 737c1e06de9e54cae3ca80f7561b7e2f4f614bb974eafd156da393bae87cf15a1faf6b06ca48d759c2519b7fbb46698f6b998d5ef14e477ab02598486f8f7338

test:
  secret_key_base: 641eb050c23c62f48634ac458a8a3acefc4c38ae5ed7ca7bd8c6a2160ea9a4bba2714bea1f44ae0c2be994b5f5f3dd35c8b25ae74087cb6d21cd55bdd6a833e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
